### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by van-den-Berg** [van-den-Berg/schweinehund_bot#2]
- [ ] Zweiten Bot erstellen zum testen neuer Entwicklungen

**Neccessary Features**
- [ ] only respond to /echo, ... if it is sent from the testing group
- [ ] Implement /weiter command
- [ ] Am Ende der Woche Lagebericht (erstmal manuell anfordern)
- [ ] Punktesystem für die Habits? (wird in Gruppe beschlossen)
- [ ] Skript, das den Bot auf dem Server restartet wenn er abkackt
- [ ] Skript zum updaten des Bots

**Additional Features**
- [ ] Nachrichten Löschen, die gesendet wurden
- [ ] Buttons zum Aktivitäten auswählen

**Comment by tim488** [comment]
- [ ] Bestätigungs Nachricht für aktivität aufhübschen. "Die Aktivität Activity.SPORT wurde erfolgreich in folgenden Gruppen hinzuefügt:
KriegDeinenArschHoch!!!, " ist nicht schön. Brauchen wir die überhaup? evtl. sollte die verschwinden...

**Comment by tim488** [comment]
- [ ] move this repository to GitLab
